---

- name: Gather facts
  ansible.builtin.gather_facts:

- name: Install Apache web server
  become: true
  ansible.builtin.package:
    name: httpd
    state: present

- name: Ensure Apache is started and enabled on boot
  become: true
  ansible.builtin.service:
    name: "httpd"
    state: "started"
    enabled: true

- name: Create default index.html
  become: true
  ansible.builtin.copy:
    content: |
      <html>
      <body>
        <h1>Welcome to Apache on AlmaLinux!</h1>
      </body>
      </html>
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: default_page

- name: Restart Apache service
  become: true
  when: default_page.changed
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: Display VM IP address
  ansible.builtin.debug:
    var: ansible_all_ipv4_addresses

...
